### ISSUE TITLE
W1/EX2: JavaScript

### ISSUE THREAD

**Issue by KrijnHoetmer** [SadisticSun/Browser-Technologies#4]
> Wanneer JS uitgeschakeld is functioneert de app niet meer. Er wordt geen data meer ingeladen en de app blijft op het startscherm hangen.

En hoe zou je dat kunnen oplossen?

**Comment by TristanJacobs89** [comment]
Serverside rendering, of een andere taal (PHP, Ruby, Python)  gebruiken.
