### ISSUE TITLE
2.1: Event.preventDefault()

### ISSUE THREAD

**Issue by KrijnHoetmer** [SadisticSun/Browser-Technologies#8]
Did you test this demo in IE8 (the last IE version that doesn't support `preventDefault`)? It's not that interesting of course, but since you picked this feature, I wonder how you tested it.

Hint: IE8 doesn't support `addEventListener` either..

**Comment by TristanJacobs89** [comment]
Fixed it! 
Works in IE8 now :)
addEvenListener has a feature check too, and a fallback to attachEvent.
